- name: Enroll app host into IPA
  hosts: app
  become: true
  vars:
    ipa_domain: "lab.evgenii.org"
    ipa_realm: "LAB.EVGENII.ORG"
    ipa_fqdn: "ipa.lab.evgenii.org"
    app_fqdn: "app.lab.evgenii.org"
    ipa_admin_password: "Admin_P@ss"

  pre_tasks:
    - name: Set app hostname
      ansible.builtin.hostname:
        name: "{{ app_fqdn }}"

    - name: Ensure /etc/hosts has app FQDN
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_host }} {{ app_fqdn }} app"
        state: present

    - name: Ensure /etc/hosts has IPA FQDN
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars['rocky'].ansible_host }} {{ ipa_fqdn }} rocky"
        state: present

    - name: Ensure freeipa-client package
      package:
        name: freeipa-client
        state: present

    - name: Ensure /etc/ipa directory exists
      ansible.builtin.file:
        path: /etc/ipa
        state: directory
        mode: '0755'

    - name: Copy IPA CA from server
      fetch:
        src: /etc/ipa/ca.crt
        dest: /tmp/ca.crt
        flat: yes
      delegate_to: rocky

    - name: Ensure /etc/ipa/ca.crt present
      copy:
        src: /tmp/ca.crt
        dest: /etc/ipa/ca.crt
        mode: "0644"

    - name: Verify certificate was copied
      stat:
        path: /etc/ipa/ca.crt
      register: cert_stat
      failed_when: not cert_stat.stat.exists

  tasks:
    - name: Enroll with ipa-client-install
      command: >
        ipa-client-install -U
        --server={{ ipa_fqdn }}
        --domain={{ ipa_domain }}
        --realm={{ ipa_realm }}
        --principal=admin
        --password={{ ipa_admin_password }}
        --mkhomedir
        --ca-cert-file=/etc/ipa/ca.crt
      args:
        creates: /etc/ipa/default.conf
