- name: Enroll app host into IPA
  hosts: app
  become: true
  vars:
    ipa_domain: "lab.evgenii.org"
    ipa_realm: "LAB.EVGENII.ORG"
    ipa_fqdn: "ipa.lab.evgenii.org"
    app_fqdn: "app.lab.evgenii.org"
    ipa_admin_password: "Admin_P@ss"

  pre_tasks:
    - name: Set app hostname
      ansible.builtin.hostname:
        name: "{{ app_fqdn }}"

    - name: Ensure /etc/hosts has app FQDN
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_host }} {{ app_fqdn }} app"
        state: present

    - name: Ensure /etc/hosts has IPA FQDN
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars['rocky'].ansible_host }} {{ ipa_fqdn }} rocky"
        state: present

    - name: Ensure freeipa-client package
      package:
        name: freeipa-client
        state: present

    - name: Ensure /etc/ipa directory exists
      ansible.builtin.file:
        path: /etc/ipa
        state: directory
        mode: "0755"

    - name: Remove stale /etc/ipa/ca.crt if present
      file:
        path: /etc/ipa/ca.crt
        state: absent

    - name: Download IPA CA directly from server (HTTP)
      get_url:
        url: "http://{{ ipa_fqdn }}/ipa/config/ca.crt"
        dest: /etc/ipa/ca.crt
        mode: "0644"
        timeout: 30

    - name: Validate CA with openssl
      command: openssl x509 -in /etc/ipa/ca.crt -noout -text
      register: ca_details
      changed_when: false

    - name: Debug CA subject and issuer
      debug:
        msg: |
          Subject: {{ (ca_details.stdout | regex_search('Subject:.*')) | default('n/a') }}
          Issuer:  {{ (ca_details.stdout | regex_search('Issuer:.*'))  | default('n/a') }}

  tasks:
    - name: Enroll with ipa-client-install
      command: >
        ipa-client-install -U
        --server={{ ipa_fqdn }}
        --domain={{ ipa_domain }}
        --realm={{ ipa_realm }}
        --principal=admin
        --password={{ ipa_admin_password }}
        --mkhomedir
        --no-ntp
      args:
        creates: /etc/ipa/default.conf
