---
# Play 1: enroll APP into FreeIPA
- name: Enroll app host into IPA
  hosts: app
  become: true
  vars:
    ipa_base_domain: "evgenii.org"
    ipa_subdomain: "lab"
    ipa_domain: "{{ ipa_subdomain }}.{{ ipa_base_domain }}"
    ipa_realm: "{{ (ipa_subdomain + '.' + ipa_base_domain) | upper }}"
    ipa_host: "rocky"
    ipa_fqdn: "ipa.{{ ipa_subdomain }}.{{ ipa_base_domain }}"
    app_fqdn: "app.{{ ipa_subdomain }}.{{ ipa_base_domain }}"

  pre_tasks:
    - name: Set app hostname to desired FQDN
      command: hostnamectl set-hostname {{ app_fqdn }}

    - name: Ensure /etc/hosts has app FQDN mapped to its IP
      lineinfile:
        path: /etc/hosts
        regexp: '^{{ hostvars[inventory_hostname].ansible_host | regex_escape() }}\s+'
        line: "{{ hostvars[inventory_hostname].ansible_host }} {{ app_fqdn }} app"
        state: present
        create: yes
        backrefs: yes

    - name: Ensure /etc/hosts has IPA FQDN mapped to its IP
      lineinfile:
        path: /etc/hosts
        regexp: '^{{ hostvars[ipa_host].ansible_host | regex_escape() }}\s+'
        line: "{{ hostvars[ipa_host].ansible_host }} {{ ipa_fqdn }} rocky"
        state: present
        create: yes
        backrefs: yes

    - name: Ensure FreeIPA client package is present
      apt:
        update_cache: true
        name: freeipa-client
        state: present

    - name: Read IPA CA from server
      slurp:
        src: /etc/ipa/ca.crt
      register: ipa_ca
      delegate_to: rocky

    - name: Ensure /etc/ipa exists
      file:
        path: /etc/ipa
        state: directory
        mode: "0755"

    - name: Write IPA CA certificate to app host
      copy:
        dest: /etc/ipa/ca.crt
        content: "{{ ipa_ca.content | b64decode }}"
        mode: "0644"

  tasks:
    - name: Enroll with ipa-client-install (idempotent via creates)
      command: >
        ipa-client-install -U
        --server={{ ipa_fqdn }}
        --domain={{ ipa_domain }}
        --realm={{ ipa_realm }}
        --principal=admin
        --password={{ ipa_admin_password }}
        --mkhomedir
        --ca-cert-file=/etc/ipa/ca.crt
      args:
        creates: /etc/ipa/default.conf
