- name: Configure HBAC on IPA server
  hosts: rocky
  become: true
  vars:
    app_host: "app"
    app_fqdn: "app.lab.evgenii.org"
    ipa_admin_password: "Admin_P@ss"

  tasks:
    - name: kinit admin (non-interactive)
      no_log: true
      shell: echo "{{ ipa_admin_password }}" | kinit admin
      changed_when: false

    - name: Ensure HBAC rule exists
      shell: ipa hbacrule-add allow-ssh-to-app --desc="Allow SSH to app host" || true
      changed_when: false

    - name: Bind HBAC rule to app host + sshd service
      shell: |
        ipa hbacrule-mod allow-ssh-to-app --hostcat=none || true
        ipa hbacrule-add-host allow-ssh-to-app --hosts='{{ app_fqdn }}' || true
        ipa hbacrule-mod allow-ssh-to-app --servicecat=none || true
        ipa hbacrule-add-service allow-ssh-to-app --hbacsvcs=sshd || true
      changed_when: false

    - name: Add users to HBAC rule
      shell: |
        ipa hbacrule-add-user allow-ssh-to-app --users=user1 || true
        ipa hbacrule-add-user allow-ssh-to-app --users=user2 || true
        ipa hbacrule-add-user allow-ssh-to-app --users=user3 || true
      changed_when: false

    - name: Set ACLs for users
      ansible.posix.acl:
        path: /app
        entity: "{{ item.user }}"
        etype: user
        permissions: "{{ item.perms }}"
        state: present
      loop:
        - { user: "user1", perms: "rx" }
        - { user: "user2", perms: "rwx" }
        - { user: "user3", perms: "rwx" }

    - name: Set default ACLs
      ansible.posix.acl:
        path: /app
        entity: "{{ item.user }}"
        etype: user
        permissions: "{{ item.perms }}"
        default: yes
        state: present
      loop:
        - { user: "user1", perms: "rx" }
        - { user: "user2", perms: "rwx" }
        - { user: "user3", perms: "rwx" }
